language: c++
script: make
arch:
  - amd64
  - arm64
os: linux
before_install:
  - sudo apt-get update
  - sudo apt-get -y install gcc make
  - if [ "$(uname -m)" = "x86_64" ]; then sudo apt-get -y install g++-aarch64-linux-gnu; fi